version: '2'

services:
  ci-build:
    image: microsoft/aspnetcore-build:${DOTNET_VERSION}
    container_name: build
    volumes:
     - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ${SLN_FILE} && dotnet publish ${SLN_FILE} -c Release -o ${OUTPUT_PATH}"