version: '2'

services:
  ci-unit-tests:
    image: microsoft/dotnet:${DOTNET_SDK_VERSION}-sdk
    container_name: unittests
    volumes:
     - .:/src
    working_dir: /src
    command: sh run-unit-tests.sh
