version: '2'

services:
  ci-integration-tests:
    image: microsoft/dotnet:${DOTNET_SDK_VERSION}-sdk-jessie
    network_mode: bridge
    container_name: integrationtests
    volumes:
     - .:/src
    working_dir: /src
    environment:
     - 'MTS_APP_SETTINGS_ConsulStoreConfiguration:Environment=${CONSUL_ENVIRONMENT}'
     - 'MTS_APP_SETTINGS_ConsulClientConfiguration:Address=${CONSUL_ADDRESS}'
    external_links:
     - ${CONTAINER_NAME}
    command: ./run-integration-tests.sh
