version: '2'

services:
  ci-integration-tests:
    image: microsoft/dotnet:${DOTNET_VERSION}
    network_mode: bridge
    container_name: integrationtests
    volumes:
     - .:/src
    working_dir: /src
    env_file:
     - integrationtestsparams.env
    external_links:
     - ${CONTAINER_NAME}
    command: sh run-integration-tests.sh
